imx8mq: clock: To fix compile error for DSI and imx8mq
fix compile error of:
drivers/video/nxp/imx/sec_mipi_dsim.o: In function `sec_mipi_dsim_calc_pmsk':
/home/joezhang/workspace/uboot-imx-edm/drivers/video/nxp/imx/sec_mipi_dsim.c:678: undefined reference to `get_dsi_phy_ref_clk'

This patch is refer to these patch:
commit 295fbe15ea8db49979314cf6b7e660926503f022
Author: Ye Li <ye.li@nxp.com>
Date:   Wed Aug 25 10:37:02 2021 +0800

    LFU-247-1 imx8m: clock: Add function to get DSI PHY reference clock rate

    The D-PHY ref clock source is configurable. We need to know the reference
    clock rate for D-PHY PLL calculation.

    Signed-off-by: Ye Li <ye.li@nxp.com>
    Reviewed-by: Peng Fan <peng.fan@nxp.com>
    (cherry picked from commit 2560cd096e54d21d5b68fd3cb70e4d3140854bc3)